### PR TITLE
SPARKC-396: Upgrade to Spark 2.0.0-preview

### PR DESCRIPTION
**Pull request by jacek-lewandowski**
- Removed Twitter demo because there is no spark-streaming-twitter package available anymore
- Removed Akka Actor demo becaues there is no support for such streams anymore
- Bring back Kafka project and make it compile
- Update several classes to use our Logging instead of Spark Logging because Spark Logging became private
- Update few components and tests to make them work with Spark 2.0.0
- Fix Spark SQL - temporarily
- Update plugins and Scala version

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
2.10 vs 2.11 issues it looks like :( 

```
14:10:28 [error] /jenkins_data/jenkins/workspace/DSE_SparkCassandraConnector_2.10_PullRequest_Builder/spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/repl/CassandraRDDReplSpec.scala:24: too many arguments for method runInterpreter: (input: String)String
14:10:28 [error]     val output = runInterpreter(
14:10:28 [error]                                ^
14:10:37 [error] one error found
14:10:37 [error] (spark-cassandra-connector/it:c
```

**Comment by RussellSpitzer** [comment]
and assembly getting confused about netty-all vs subcomponents
{code}
[error] (spark-cassandra-connector/*:assembly) deduplicate: different file contents found in the following:
[error] /home/travis/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.0.29.Final.jar:io/netty/bootstrap/AbstractBootstrap$1.class
[error] /home/travis/.ivy2/cache/io.netty/netty-transport/jars/netty-transport-4.0.33.Final.jar:io/netty/bootstrap/AbstractBootstrap$1.class
{code}

**Comment by RussellSpitzer** [comment]
lgtm +1
